# https://github.com/ls-lint/docs

ls:
  # keep-sorted start
  .css: kebab-case
  .html: kebab-case
  .json: kebab-case
  .sh: snake_case
  .toml: kebab-case
  .yaml: kebab-case
  .yml: kebab-case
  # keep-sorted end

ignore:
  # keep-sorted start
  - layouts
  - vendor
  # keep-sorted end
