# https://github.com/ls-lint/docs

ls:
  # keep-sorted start
  .sh: snake_case
  .yaml: kebab-case
  .yml: kebab-case
  # keep-sorted end

ignore:
  # keep-sorted start
  - vendor
  # keep-sorted end
