# yaml-language-server: $schema=schemas/markdownlint-config-schema.json

# https://github.com/DavidAnson/markdownlint-cli2#configuration
config:
  # TODO: Enable more lint rules.
  # keep-sorted start
  MD010: false
  MD012: false
  MD013: false
  MD014: false
  MD022: false
  MD027: false
  MD028: false
  MD029: false
  MD032: false
  MD033: false
  MD034: false
  MD036: false
  MD040: false
  MD041: false
  MD046: false
  MD053: false
  # keep-sorted end
