# yaml-language-server: $schema=schemas/markdownlint-config-schema.json

# https://github.com/DavidAnson/markdownlint-cli2#configuration
config:
  # These must be kept. This list was triaged on 2025-09-05.
  # keep-sorted start
  MD010: false
  MD013: false
  MD014: false
  MD028: false
  MD029: false
  MD033: false
  MD034: false
  MD036: false
  MD040: false
  MD041: false
  MD046: false
  # keep-sorted end
