# yaml-language-server: $schema=https://raw.githubusercontent.com/DavidAnson/markdownlint/main/schema/markdownlint-config-schema.json

# https://github.com/DavidAnson/markdownlint-cli2#configuration
config:
  # keep-sorted start
  MD010: false
  MD012: false
  MD013: false
  MD014: false
  MD022: false
  MD027: false
  MD028: false
  MD029: false
  MD032: false
  MD033: false
  MD034: false
  MD036: false
  MD037: false
  MD038: false
  MD040: false
  MD041: false
  MD042: false
  MD045: false
  MD046: false
  MD047: false
  MD049: false
  MD053: false
  # keep-sorted end
