StylesPath = .vale/styles
MinAlertLevel = suggestion

Packages = Hugo, write-good

[content/posts/*.md]
BasedOnStyles = Vale, write-good

# keep-sorted start
Vale.Spelling = NO
write-good.So = NO
# keep-sorted end
