baseURL = 'https://thiagowfx.github.io/'
copyright = '© 2021 Thiago Perrotta'
enableRobotsTxt = true
languageCode = 'en-us'
paginate = 10
rssLimit = 20
theme = 'PaperMod'
title = 'Not Just Serendipity'

[author]
email = 'tbperrotta@gmail.com'
name = 'Thiago Perrotta'

[permalinks]
posts = '/:year/:month/:title/'

[params]
author = 'Thiago Perrotta'
showFullTextinRss = true

[menu]
[[menu.main]]
identifier = 'tags'
name = 'Tags'
url = '/tags/'
