baseURL = 'https://thiagowfx.github.io/'
copyright = '© 2021 Thiago Perrotta'
languageCode = 'en-us'
title = 'Not Just Serendipity'
paginate = 10
rssLimit = 20
theme = 'mainroad'

[author]
email = 'tbperrotta@gmail.com'
name = 'Thiago Perrotta'
