baseURL = 'https://thiagowfx.github.io/'
copyright = '© 2021 Thiago Perrotta'
enableRobotsTxt = true
languageCode = 'en-us'
paginate = 10
rssLimit = 20
theme = 'PaperMod'
title = 'Not Just Serendipity'

[author]
email = 'tbperrotta@gmail.com'
name = 'Thiago Perrotta'

[menu]
[[menu.main]]
identifier = 'posts'
name = 'Posts'
url = '/posts/'

[[menu.main]]
identifier = 'rss'
name = 'RSS'
url = '/index.xml'

[[menu.main]]
identifier = 'tags'
name = 'Tags'
url = '/tags/'

[params]
author = 'Thiago Perrotta'
disableSpecial1stPost = true
showCodeCopyButtons = true
showFullTextinRss = true
showReadingTime = true

[[params.socialIcons]]
name = 'github'
url = 'https://github.com/thiagowfx'

[permalinks]
posts = '/:year/:month/:title/'
