baseURL = 'https://thiagowfx.github.io/'
copyright = 'Copyright © 2021 Thiago Perrotta • All rights reserved • [Source](https://github.com/thiagowfx/thiagowfx.github.io/) • '
enableRobotsTxt = true
languageCode = 'en-us'
paginate = 10
rssLimit = 20
theme = 'PaperMod'
title = 'Not Just Serendipity'

[author]
email = 'tbperrotta@gmail.com'
name = 'Thiago Perrotta'

[menu]
[[menu.main]]
identifier = 'Archives'
name = 'Archives'
url = '/archives/'
weight = 1

[[menu.main]]
identifier = 'tags'
name = 'Tags'
url = '/tags/'
weight = 1

[params]
author = 'Thiago Perrotta'
comments = true
keywords = ['blog', 'linux', 'open source', 'thiago perrotta']
disableSpecial1stPost = true
showCodeCopyButtons = true
showFullTextinRss = true
showReadingTime = true

[params.assets]
favicon16x16 = "/favicon.ico"
favicon32x32 = "/favicon.ico"

[params.editPost]
appendFilePath = true
text = "Suggest an improvement"
url = "https://github.com/thiagowfx/thiagowfx.github.io/edit/master/content/"

[params.homeInfoParams]
Title = 'Thiago Perrotta'

[params.label]
icon = "/apple-touch-icon.png"
iconHeight = 32

[[params.socialIcons]]
name = 'github'
url = 'https://github.com/thiagowfx'

[[params.socialIcons]]
name = 'rss'
url = '/index.xml'

[permalinks]
posts = '/:year/:month/:title/'

[params.schema]
publisherType = 'Person'
