<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:atom="http://www.w3.org/2005/Atom">
  <xsl:output method="html" doctype-public="-//W3C//DTD HTML 4.01 Transitional//EN" doctype-system="http://www.w3.org/TR/html4/loose.dtd" indent="yes"/>

  <xsl:template match="/">
    <html>
      <head>
        <title><xsl:value-of select="rss/channel/title"/> - RSS Feed</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <style type="text/css">
          body {
            font-family: Georgia, 'Times New Roman', Times, serif;
            line-height: 1.6;
            color: #333;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background: #fff;
          }

          .header {
            border-bottom: 2px solid #ddd;
            margin-bottom: 30px;
            padding-bottom: 20px;
          }

          .header h1 {
            margin: 0;
            color: #2c3e50;
            font-size: 2.2em;
          }

          .header p {
            margin: 10px 0 0;
            color: #666;
            font-size: 1.1em;
          }

          .feed-info {
            background: #f8f9fa;
            border: 1px solid #e9ecef;
            border-radius: 5px;
            padding: 20px;
            margin-bottom: 30px;
          }

          .feed-info h2 {
            margin-top: 0;
            color: #495057;
          }

          .feed-url {
            background: #fff;
            border: 1px solid #ced4da;
            padding: 10px;
            border-radius: 3px;
            font-family: monospace;
            word-break: break-all;
          }

          .item {
            border-bottom: 1px solid #eee;
            padding: 20px 0;
          }

          .item:last-child {
            border-bottom: none;
          }

          .item h3 {
            margin: 0 0 10px;
            font-size: 1.4em;
          }

          .item h3 a {
            color: #2c3e50;
            text-decoration: none;
          }

          .item h3 a:hover {
            color: #3498db;
            text-decoration: underline;
          }

          .item-meta {
            color: #666;
            font-size: 0.9em;
            margin-bottom: 15px;
          }

          .item-description {
            color: #333;
            line-height: 1.7;
          }

          .item-description p:first-child {
            margin-top: 0;
          }

          .item-description p:last-child {
            margin-bottom: 0;
          }

          .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            text-align: center;
            color: #666;
            font-size: 0.9em;
          }

          @media (max-width: 600px) {
            body {
              padding: 15px;
            }

            .header h1 {
              font-size: 1.8em;
            }

            .item h3 {
              font-size: 1.2em;
            }
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1><xsl:value-of select="rss/channel/title"/></h1>
          <p><xsl:value-of select="rss/channel/description"/></p>
        </div>

        <div class="feed-info">
          <h2>📡 RSS Feed</h2>
          <p>This is an RSS feed. You can subscribe to it using your favorite RSS reader to get updates when new posts are published.</p>
          <p><strong>Feed URL:</strong></p>
          <div class="feed-url">
            <xsl:value-of select="rss/channel/atom:link/@href"/>
          </div>
          <p style="margin-bottom: 0;">
            <a href="{rss/channel/link}">← Back to website</a>
          </p>
        </div>

        <xsl:for-each select="rss/channel/item">
          <div class="item">
            <h3>
              <a href="{link}" target="_blank">
                <xsl:value-of select="title"/>
              </a>
            </h3>

            <div class="item-meta">
              <xsl:if test="author">
                <strong>By:</strong> <xsl:value-of select="author"/> •
              </xsl:if>
              <strong>Published:</strong> <xsl:value-of select="pubDate"/>
            </div>

            <div class="item-description">
              <xsl:value-of select="description" disable-output-escaping="yes"/>
            </div>
          </div>
        </xsl:for-each>

        <div class="footer">
          <p>
            Generated by <a href="https://gohugo.io/" target="_blank">Hugo</a> •
            Last updated: <xsl:value-of select="rss/channel/lastBuildDate"/>
          </p>
          <xsl:if test="rss/channel/copyright">
            <p><xsl:value-of select="rss/channel/copyright"/></p>
          </xsl:if>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>